name: Cargo Build & Test

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Installing Rust toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Installing Rust fmt
        run: rustup component add rustfmt
      - name: Installing Rust clippy
        run: rustup component add clippy
      - name: Build project
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run formatting checks
        run: cargo fmt --all --check
      - name: Run clippy
        run: cargo clippy --no-deps
